### PR TITLE
fix(model schema): improve model schema

### PR DESCRIPTION
**Pull request by mostaphaRoudsari**
I made a number of changes to model schema to make it more restrict. Here is the list:
1. rad_modifier shouldn't be required and will be set based on Face.face_type. I tried to implement the
default value based on face_type and it is totally possible but mixes up the openapi documentation
so I took it out. We can take care of this by running model through a default value generator as
discussed in https://github.com/pollination/model-service/issues/8
2. apertures do not need parent
object. We already know the parent which is the Face.
3. Face needs a parent which will be a zone
and is optional and only needed for energy modeling.
4. Added a validator for vertices length. Also
changed `min_items` to `minItems`.
5. Removed `Window` from FaceType enumeration and renamed it to FaceTypeOpaque.
6. Limited aperture rad_modifier to Glass and Transparent.

BREAKING CHANGE: This change will break old schema which has a parent field for apertures.

### CODE REVIEW

**Comment by AntoineDao** [comment]
Those changes make sense and I've got no objection to them. Quick question though, can we not have a glazed surface? Especially for a face by face model where users might dump walls made entirely of glass?

**Comment by mostaphaRoudsari** [comment]
Thank you for reviewing the changes.

> Quick question though, can we not have a glazed surface?

For an energy model that's invalid and for a daylight model you can do that by setting the radiance material to glass. That's why I kept the `Glass` and the `Transparent` materials for Opaque faces. 

https://github.com/pollination/model-service/pull/12/files#diff-3205309da99f8ed0a558da3df526b9c3R169

**Comment by AntoineDao** [comment]
Can we think of some clever way out of naming the face type as `FaceTypeOpaque` for something that could be glass? I can forsee this being super confusing in a couple of month's time.

**Comment by mostaphaRoudsari** [comment]
I can think of two options:

1. Changing it back to `FaceType`
2. `FaceTypeNonAperture`?

**Comment by AntoineDao** [comment]
Is it ok if we make it `FaceType`?

**Comment by mostaphaRoudsari** [comment]
Done! Changed it back to `FaceType`.

**Comment by mostaphaRoudsari** [comment]
@AntoineDao can we merge this in?

**Pull request merged**
